name: Deploy Hostinger (Vite) - no-lockfile

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # sem cache; não requer lockfile

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Add .htaccess (SPA fallback)
        run: |
          mkdir -p dist
          cat > dist/.htaccess <<'EOF'
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^ index.html [L]
          EOF

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}   # ex.: /public_html/
          local-dir: ./dist/                          # precisa terminar com /
          dangerous-clean-slate: true
